### ISSUE TITLE
[Checklist] Upgrade SVN to 1.5.9

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/landing-pages#128]
Check list for new version deploy
- [x]  Update main file version numbers
- [x]  Update readme.txt & change log from viewing closed github issues. 
- [x]  Update change log on docs.inboundnow.com: http://docs.inboundnow.com/changelogs/landing-pages-cl/
- [x] Test new version installation against older released versions of Leads and CTA
- [x]  Make sure all landing pages & variations are in tact.
- [x]  Manual Unit Tests
  - [x] Landing pages load without 404 errors
  - [x]  Variations rotate.
  - [x]  Preview mode works.
  - [x] Customizer works.
  - [x] Impressions track
  - [x]  Conversions track
- [ ]  Install latest leads & cta & repeat manual unit tests above. 
  - [x] Landing pages load without 404 errors
  - [x]  Variations rotate.
  - [x]  Preview mode works.
  - [x] Customizer works.
  - [x] Impressions track
  - [x]  Conversions track
- [ ]  Deploy plugin update. 
- [ ] Announce plugin update to Twitter.
- [ ]  Announce plugin update to Facebook. 
- [ ]  Announce plugin update to Email?
